# mkdocs.yml
site_name: gopiq - Go Image Processing
site_url: https://TamasGorgics.github.io/gopiq/
repo_url: https://github.com/TamasGorgics/gopiq
repo_name: TamasGorgics/gopiq
edit_uri: ""
docs_dir: '.'
site_dir: ../site

theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt

nav:
  - 'Home': 'index.md'
  - 'API Reference':
    - 'Core Methods': 'api/core.md'
    - 'Processing Operations': 'api/operations.md'
    - 'Watermark Options': 'api/watermark.md'
  - 'Performance': 'performance.md'
  - 'Concurrency': 'concurrency.md'

extra_css:
  - assets/custom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true 