# .github/workflows/docs.yml
name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install documentation dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build MkDocs site
        run: |
          mkdocs build -f docs/mkdocs.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # Optional: You can add a custom commit message
          # commit_message: 'Deploy documentation: ${{ github.event.head_commit.message }}' 